### ISSUE TITLE
获取record_id为空,可能没有获取到有效的解析记录(record_id=)

### ISSUE THREAD

**Issue by papersnake** [risfeng/aliyun-ddns-shell#1]
运行出现如下错误 
获取record_id为空,可能没有获取到有效的解析记录(record_id=)

> [Info]    2020-04-16 23:01:24 检测到配置文件,自动加载现有配置信息。可通过菜单选项【恢复出厂设置】重置.
[Info]    2020-04-16 23:01:24 正在尝试检测外网:ping www.baidu.com 1 times......
[Success] 2020-04-16 23:01:24 检测外网成功!
[Info]    2020-04-16 23:01:24 正在获取本机外网ip......
[Info]    2020-04-16 23:01:24 本机外网ip:180.106.51.27
[Info]    2020-04-16 23:01:24 正在获取cloud.wx2share.com的ip......
[Info]    2020-04-16 23:01:24 域名cloud.wx2share.com的当前ip:0.0.0.0
[Info]    2020-04-16 23:01:24 正在更新域名解析记录值......
[Info]    2020-04-16 23:01:24 正在获取record_id......
[Warning] 2020-04-16 23:01:24 获取record_id为空,可能没有获取到有效的解析记录(record_id=)
[Failed]  2020-04-16 23:01:24 域名解析记录更新失败!
[Info]    2020-04-16 23:01:24 正在推送消息到钉钉......

**Comment by papersnake** [comment]
不好意思，是我没有给我的域名子用户足够权限所导致的，谢谢你的脚本

**Comment by ddouweb** [comment]
我给了权限了。还是不行。之前是uuidgen没有安装。我使用了固定的uuid。现在装了uuidgen。还是获取不到。难受啊，求助
