### ISSUE TITLE
curl -s http://members.3322.org/dyndns/getip 返回404找不到页面

### ISSUE THREAD

**Issue by bksy0909** [risfeng/aliyun-ddns-shell#28]
你好：
这个程序至少稳定运行了一年多，今天突然发现不正常了。
1)我检查了log ，发现我的环境，发现
curl -s http://members.3322.org/dyndns/getip 运行后返回的是404 的html。log如图
2) 我实际用终端运行这句,也是返回404 的html
请帮看下要怎么解决 ？ 谢谢！
![image](https://user-images.githubusercontent.com/48849993/184539380-034cb7b6-2d48-4376-abb4-4c252a0dc3eb.png)

**Comment by bksy0909** [comment]
补充一下，ping  members.3322.org 可以成功

**Comment by bksy0909** [comment]
我找到这个网址 似乎可用，先用这个替代下 curl ifconfig.me
如果有更好 更稳定的，也请帮说明下 
谢谢！

**Comment by risfeng** [comment]
> 

你把代码改成使用这个curl ifconfig.me 目前这个比较稳～
