### ISSUE TITLE
aliyun-ddns.sh: line 670: uuidgen: command not found

### ISSUE THREAD

**Issue by jamsread** [risfeng/aliyun-ddns-shell#5]

**Comment by risfeng** [comment]
What operating system?

**Comment by risfeng** [comment]
> _No description provided._
What operating system?

**Comment by jamsread** [comment]
rapberry4 （debian）

**Comment by risfeng** [comment]
> rapberry4 （debian）

I don't have a Raspberry Pi environment, but you can try this command `sudo apt-get install uuid-runtime`
