### ISSUE TITLE
配置文件配完了在哪里?

### ISSUE THREAD

**Issue by azhenge** [risfeng/aliyun-ddns-shell#6]

**Comment by azhenge** [comment]
我不需要二级域名, 必填咋办

**Comment by azhenge** [comment]
[Warning] 2020-07-25 23:45:58 获取record_id为空,可能没有获取到有效的解析记录(record_id=)

**Comment by risfeng** [comment]
> 我不需要二级域名, 必填咋办

不可能没有二级域名的，
根解析：@  
泛解析：*

**Comment by risfeng** [comment]
> 为

有可能你阿里云没有默认配置一条解析记录，更新时就会报record_id为空。

**Comment by risfeng** [comment]
> _No description provided._
配置文件路径：
/etc/config.cfg 或 ~/config.cfg
