### ISSUE TITLE
我想解析IPV6可以嘛？

### ISSUE THREAD

**Issue by ghost** [risfeng/aliyun-ddns-shell#7]

**Comment by risfeng** [comment]
> _No description provided._

可以，需要自己修改 获取外网IPV6地址的接口。

**Comment by ghost** [comment]
大佬，还请您出山吧！您的配置绕的我头痛
http://v6.meibu.com/ips.asp
这个是v6接口！

**Comment by ghost** [comment]
好东西已经star

**Comment by risfeng** [comment]
> 大佬，还请您出山吧！您的配置绕的我头痛
> http://v6.meibu.com/ips.asp
> 这个是v6接口！

我晚上试试吧。

**Comment by ghost** [comment]
@risfeng 感谢大佬

**Comment by risfeng** [comment]
> @risfeng 感谢大佬

代码提交了，我没有IPV6，你试试。
